language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install numpy pytest tensorflow

cache: pip

script:
  - pytest --ignore groupy/gconv/gconv_chainer/ --ignore groupy/gconv/gconv_tensorflow/test_transform_filter.py
